package main;

public enum ConnectionResult {
	UNKNOWN,
	SUCCESS,
	SERVER_UNSELECTABLE,
	SERVER_SAVING,
	SERVER_OFFLINE_OR_FULL,
	ACCOUNT_BANNED_DEFINITIVELY,
	ACCOUNT_BANNED_TEMPORARILY,
	AUTHENTIFICATION_FAILED
}