package main;

public enum Event {
	TIMEOUT,
	CHARACTER_LOADED,
	MOVEMENT_DONE,
	FIGHT_START,
	FIGHT_END,
	GAME_TURN_START,
	GAME_TURN_END,
	LIFE_REGENERATION_COMPLETE,
	MONSTER_GROUP_RESPAWN,
	WEIGHT_MAX,
	LEVEL_UP
}