package controller;

public enum CharacterState {
	IS_FREE,
	IS_LOADED,
	IN_MOVEMENT,
	IN_FIGHT,
	IN_GAME_TURN,
	IN_REGENERATION,
	NEED_TO_EMPTY_INVENTORY,
	LEVEL_UP,
	PENDING_DEMAND,
	IN_EXCHANGE,
	EXCHANGE_VALIDATED,
	NEW_ACTOR_ON_MAP,
	MULE_AVAILABLE
}