package controller;

public enum CharacterState {
	IS_FREE,
	IS_LOADED,
	IN_FIGHT,
	IN_PARTY,
	NOT_IN_PARTY,
	IN_GAME_TURN,
	NEED_TO_EMPTY_INVENTORY,
	LEVEL_UP,
	PENDING_DEMAND,
	IN_EXCHANGE,
	EXCHANGE_VALIDATED,
	MULE_AVAILABLE,
	CAN_MOVE,
	
	NEW_ACTOR_ON_MAP,
	NEW_ACTOR_IN_FIGHT,
	CAPTAIN_ACT,
	NEW_PARTY_MEMBER,
	FIGHT_LAUNCHED,
	SPELL_CASTED,
	WHOIS_RESPONSE
}