package controller;

public enum CharacterState {
	IS_LOADED,
	IN_FIGHT,
	IN_EXCHANGE,
	NOT_IN_EXCHANGE,
	IN_PARTY,
	NOT_IN_PARTY,
	IN_REGENERATION,
	IN_GAME_TURN,
	NEED_TO_EMPTY_INVENTORY,
	LEVEL_UP,
	PENDING_DEMAND,
	EXCHANGE_VALIDATED_BY_PEER,
	SHOULD_DECONNECT,
	DIALOG_DISPLAYED,
	
	// events
	NEW_ACTOR_ON_MAP,
	NEW_ACTOR_IN_FIGHT,
	CAPTAIN_ACT,
	SOLDIER_ACT,
	NEW_PARTY_MEMBER,
	FIGHT_LAUNCHED,
	SPELL_CASTED,
	WHOIS_RESPONSE,
	EXCHANGE_ACTION_RESPONSE,
	EXCHANGE_DEMAND_OUTCOME,
}