package controller;

public enum Event {
	CHARACTER_LOADED,
	FIGHT_START,
	FIGHT_END,
	GAME_TURN_START,
	WEIGHT_MAX,
	LEVEL_UP,
	EXCHANGE_DEMAND,
	EXCHANGE_START,
	EXCHANGE_VALIDATION,
	EXCHANGE_LEAVE,
	NEW_ACTOR
}